### ISSUE TITLE
Basic NSFW option

### ISSUE THREAD

**Issue by Andre601** [Chew/JDA-Chewtils#14]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming features and updates.

### Affected Modules

Command

### Description

(First issue with new template. Wohoo!)

The SlashCommand should have a `this.nsfw` boolean option to set if the command is only executable within NSFW channels.

While Discord hasn't added any option yet to set a Command for NSFW only (See https://github.com/discord/discord-api-docs/discussions/3312 for the feature request about that) should JDA-Chewtils still do some basic handling of the SlashCommand to make sure that the channel is NSFW if the `this.nsfw` boolean is true.

Chewtils could just respond with a (customizable?) error message regarding this.

Code Example:
```java
public class CommandNsfw extends SlashCommand {
    
    public CommandNsfw() {
        this.name = "nsfw";
        this.help = "Some naughty command.";
        this.nsfw = true;
    }
    
    @Override
    public void execute(SlashCommandEvent event) {
        // Stuff
    }
}
```

**Comment by Chew** [comment]
This could probably be added to the Command class, then just handle it normally. When Discord adds support, it can be baked in natively.
`this.nsfwOnly = true` likely.
What should the message be? "This command may only be ran in a NSFW text channel or server!"

**Comment by Andre601** [comment]
Probably
