### ISSUE TITLE
Please use latest gradle/jda version

### ISSUE THREAD

**Issue by kxmpxtxnt** [Chew/JDA-Chewtils#23]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Examples

**Comment by Chew** [comment]
We are 3 major versions behind with Gradle. If you (or someone) wants to take on that task by all means have fun:
[![image](https://user-images.githubusercontent.com/8278263/131284357-e5c52ebf-ba39-4357-9044-c8dc244cf850.png)](https://docs.gradle.org/current/userguide/upgrading_version_4.html)

In the meantime, just use the wrapper.

As for the JDA, just bundle your own [like I do here](https://github.com/Chewbotcca/Discord/blob/main/pom.xml#L38-L50).

You definitely shouldn't be relying on the dependencies of this project, honestly.
