### ISSUE TITLE
Optional support for OptionHelper class.

### ISSUE THREAD

**Issue by portlek** [Chew/JDA-Chewtils#36]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming features and updates.

### Affected Modules

Command

### Description

Add java.util.Optional<T> return type for each opt*** methods. For example;
```java
    /**
     * Guarantees a String option value by providing a default value.
     *
     * @param event        The slash command event to get options from
     * @param option       The option we want
     * @param defaultValue The fallback option in case of the absence of the option value
     * @return The provided option, or the default value if the option is not present
     */
    @Nullable
    @Contract("_, _, !null -> !null")
    public static String optString(@NotNull SlashCommandEvent event, @NotNull String option, @Nullable String defaultValue) {
        List<OptionMapping> options = event.getOptionsByName(option);

        return options.isEmpty() ? defaultValue : options.get(0).getAsString();
    }

    /**
     * Guarantees a String option value by providing a default value.
     *
     * @param event        The slash command event to get options from
     * @param option       The option we want
     * @param defaultValue The fallback option in case of the absence of the option value
     * @return The provided option, or the default value if the option is not present
     */
    @NotNull
    public static Optional<String> optString(@NotNull SlashCommandEvent event, @NotNull String option, @Nullable String defaultValue) {
        return Optional.ofNullable(optString(event, option, defaultValue));
    }

```

**Comment by Andre601** [comment]
Kinda pointless to have imo

**Comment by portlek** [comment]
it's a utility class so idk. but the purpose of this type of classes is this actually :d

**Comment by Andre601** [comment]
A simple `return OptionMapping == null ? defValue : OptionMapping#asWhatever()` is sufficient enough.
Creating an Optional just for this is a waste of time and resources.
Also,there can never be more than one OptionMapping with a specific key.

**Comment by portlek** [comment]
if you think on this class, `Optional.ofNullable(event.getOption("optionName"))` is also enough for each opt**** methods. my point is this class called helper class which can have helper methods for every option mapping related methods.

**Comment by Chew** [comment]
To my knowledge, you can't have the same method name + same parameters with a different return type.

As has been stated, I don't really see the point of this. There's a whole debate of whether Optionals are good or not, I'm on the side of don't _really_ care but optX already does everything I assume you'd want (you're guaranteed an option) which was the ultimate point of the thing.
