### ISSUE TITLE
Default @mention prefix no longer respected

### ISSUE THREAD

**Issue by brandonfl** [Chew/JDA-Chewtils#39]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Command

### Description

When I try to use the mention prefix, it dont work at all with Chewtils.
I've tryed doing the same on JDA-Utilities and it work

![image](https://user-images.githubusercontent.com/25805069/145122016-58157905-7469-48f7-a4be-6fb10b9c5904.png)

**Comment by Chew** [comment]
What are you setting your prefix to?

https://github.com/Chewbotcca/Discord/blob/main/src/main/java/pw/chew/chewbotcca/Chewbotcca.java#L90

I'm able to get it to work with `<@!clientid>`

![image](https://user-images.githubusercontent.com/8278263/145667290-497e03ec-de6c-44e2-b220-9f7ee15f8658.png)

**Comment by brandonfl** [comment]
@Chew The prefix that i've tryed are : 

- Use default prefix (dont set any prefix)
- Use the generic prefix `@mention`

In the 2 cases, it dont work.
With JDA-Utilities, if you dont set any prefix or if you set to `@mention`, the prefix is automatically changed with the client id of the bot.

Here is the code related to this feature into JDA-Utilities : 

[JDA-Applications CommandClientImpl.java line 67](https://github.com/JDA-Applications/JDA-Utilities/blob/33e05533829bd2ad44f35ff31a4793cb1ad791a2/command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java#L67) : 

![ line 67](https://user-images.githubusercontent.com/25805069/145695250-b9e20e89-52db-4f0d-95f8-200b36f02cb9.png)

[JDA-Applications CommandClientImpl.java lines 498 to 506](https://github.com/JDA-Applications/JDA-Utilities/blob/33e05533829bd2ad44f35ff31a4793cb1ad791a2/command/src/main/java/com/jagrosh/jdautilities/command/impl/CommandClientImpl.java#L498-L506) : 

![lines 498 to 506](https://user-images.githubusercontent.com/25805069/145695242-bce4fbbc-508e-4cd1-adbb-e8661e3b6b38.png)

There is no reason to have to manually set the prefix with the client id.
In my case, I provide bots on-premise, I dont want that people have to set prefix with client-id. The default prefix should do the job

**Comment by brandonfl** [comment]
Another point of the `@mention` feature is for the help builder.
It should translate the `@mention` by the `@Bot name` for exemple :  

![D0jE6NqW6m](https://user-images.githubusercontent.com/25805069/145695571-2afa9cc9-a4cb-4ca5-a7a4-e6e500bc6a86.png)

In your situation, it show : 

![DiscordCanary_AC5b4X0jdY](https://user-images.githubusercontent.com/25805069/145695582-6d162341-022b-4e35-a065-2eeaab978cb2.png)

That's **not user friendly**, like, a developper can understand it if he know how the discord api work, but not a user
