### ISSUE TITLE
Slash commands don't show up

### ISSUE THREAD

**Issue by Verdanix** [Chew/JDA-Chewtils#46]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Command

### Description

Hello,
So today I have been creating a discord bot. I need an easier way to create commands, so I chose this. When I registered the slash command and set up the bot,  and invited it multiple times, it doesn't show the command. NOTE: I am still learning Java so bear with me, please.
![image](https://user-images.githubusercontent.com/75911941/147897473-b3cb215f-efaf-4e3b-87ab-f0fba6c4a5df.png)
![image](https://user-images.githubusercontent.com/75911941/147897492-6466d77e-2d3b-488d-99e5-7e361a26c83f.png)
I put the command class in Pastebin as it was a little too large: https://pastebin.com/m9QuqcTP

**Comment by Andre601** [comment]
You have to use `build()` on the CommandClientBuilder and register it as an EventListener in JDA.

**Comment by Verdanix** [comment]
OHHHHH, Thank you so much

**Comment by Verdanix** [comment]
Wait, register the slashcommand as an eventlistener

**Comment by Andre601** [comment]
> Wait, register the slashcommand as an eventlistener

No. Read what I wrote. You build the command client and add it as event listener.

**Comment by Chew** [comment]
This file should help: https://github.com/Chewbotcca/Discord/blob/main/src/main/java/pw/chew/chewbotcca/Chewbotcca.java#L137
