### ISSUE TITLE
Context Menus not being found

### ISSUE THREAD

**Issue by Matyrobbrt** [Chew/JDA-Chewtils#48]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Command

### Description

Context menus can contain uppercase characters in their name, and when they are registered (using `CommandClient#addContextMenu`) in `contextMenuIndex` from `CommandClientImpl` the index is associated with the menu name, exactly as it is in the field (uppercased). However `CommandClientImpl#onMessageContextMenu` tries to get the index associated with the command name, **lowercased**, and such the command cannot be found if it contains uppercase characters.

__Possible ways of fixing__
- Get rid of the `toLowercase` call when the command is searched. This fix is preferred, as there could be 2 menus with the same name, but different cases
- Make `addContextMenu` lowercase the command name when inserting it in the map.

**Comment by Chew** [comment]
I'm not sure how Discord handles case sensitivity. If it allows "rory" and "Rory" as valid names then we should do the former. Should probably get rid of the checks altogether since you could have a message and user context menu with the same name and be fine.

**Comment by Matyrobbrt** [comment]
From my testing, it seems to allow 2 different commands with different letter casings

**Comment by Chew** [comment]
Indeed, this also caused issues when a User and Message context menu had the same name.
