### ISSUE TITLE
JSONObject["permissions"] is not an int when running Session#getGuilds

### ISSUE THREAD

**Issue by HeyBanditoz** [Chew/JDA-Chewtils#51]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

OAuth2

### Description

When I call `Session#getGuilds`, I get this error:
```
org.json.JSONException: JSONObject["permissions"] is not an int.
	at org.json.JSONObject.getInt(JSONObject.java:603)
	at com.jagrosh.jdautilities.oauth2.entities.impl.OAuth2ClientImpl$3.handle(OAuth2ClientImpl.java:191)
	at com.jagrosh.jdautilities.oauth2.entities.impl.OAuth2ClientImpl$3.handle(OAuth2ClientImpl.java:170)
	at com.jagrosh.jdautilities.oauth2.requests.OAuth2Requester.submitSync(OAuth2Requester.java:95)
	at com.jagrosh.jdautilities.oauth2.requests.OAuth2Action.complete(OAuth2Action.java:150)
```
I think a fix would just be to change line 191 from
`obj.getInt("permissions")));` to `obj.getLong("permissions")));` as it returns a value of `556302458433`

https://github.com/Chew/JDA-Chewtils/blob/3afd8c83d5c1de7c2b0808253ce6c9c7fd0ae196/oauth2/src/main/java/com/jagrosh/jdautilities/oauth2/entities/impl/OAuth2ClientImpl.java#L177-L195

**Comment by Chew** [comment]
Try the latest `2.0-SNAPSHOT`? Changed ints to longs but might be a breaking change so it'll get shoved into the snapshots for now.

**Comment by HeyBanditoz** [comment]
It seems to have worked, thanks!

Can't really test the rest, just playing around with OAuth2 for the first time.

**Comment by Chew** [comment]
Coolio, lemme know if you run into anything else 😄
