### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by AllRoundJonU** [Chew/JDA-Chewtils#56]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming bug fixes.

### Affected Modules

Command, Commons

### Description

If i want to start my Bot I get following Error: 
`java.lang.ClassNotFoundException: net.dv8tion.jda.api.events.message.guild.GuildMessageDeleteEvent`
I use jda-chewtils version `1.24.1`
And Version `5.0.0-alpha.4` of JDA

**Comment by Chew** [comment]
Please see https://github.com/Chew/JDA-Chewtils/wiki/Compatibility-with-JDA-4-%26-5, you need JDA-Chewtils 2.0
