### ISSUE TITLE
Add a method to override in SlashCommand for auto-completion handling

### ISSUE THREAD

**Issue by Andre601** [Chew/JDA-Chewtils#92]
### Issue Checklist

- [X] I have checked for similar issues on the [Issue tracker](https://github.com/Chew/JDA-Chewtils/issues)
- [X] I have updated to the [latest version](https://github.com/Chew/JDA-Chewtils/releases) of JDA-Chewtils.
- [X] I have checked the branches or the maintainer's PRs for upcoming features and updates.

### Affected Modules

Command

### Description

The SlashCommand class should receive a method that the dev can override to handle a CommandAutoCompleteInteractionEvent (Quite a mouth full).

The reason for this is to cut down on extra checks the dev would need to do, to know what stuff they can or cannot return here.

Effectively, JDA-Chewtil can/should do the following:

- Have the Event added to listen to.
- Once such an event is received, compare command with list of known slash commands and possibls sub-command (groups).
- If a match is found, call the method of the class for it with the Event itself provided as argument, similar to slash commands themself.
- Dev can override and handle this method.

From my thinking should this be possible technically... Just the child/sub-command (group) checking could be a bit more tricky here?
Either way, I hope this can be considered, as checking X commands and command options yourself can become a tedious task in the end...

**Comment by Chew** [comment]
I'm confused, this isn't https://github.com/Chew/JDA-Chewtils/blob/master/command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java#L155-L162 ? Or is it like that for more events?

**Comment by Andre601** [comment]
Guess I didn't look close enough. My bad.
